// Simple test script for the PDF API
const http = require('http');

const testHTML = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 40px;
            background: #f0f0f0;
        }
        h1 {
            color: #333;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .content {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div class="content">
        <h1>PDF Generator Test</h1>
        <p>This is a test document generated by the PDF Generator API.</p>
        <p>Generated at: ${new Date().toLocaleString()}</p>
    </div>
</body>
</html>
`;

const data = JSON.stringify({
  html: testHTML,
  options: {
    format: 'A4',
    printBackground: true,
    margin: {
      top: '1cm',
      right: '1cm',
      bottom: '1cm',
      left: '1cm'
    }
  }
});

const options = {
  hostname: 'localhost',
  port: 3001,
  path: '/api/generate-pdf',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': data.length
  }
};

const req = http.request(options, (res) => {
  let body = '';
  res.on('data', (chunk) => body += chunk);
  res.on('end', () => {
    console.log('Response Status:', res.statusCode);
    console.log('Response Body:', body);
    const result = JSON.parse(body);
    if (result.success) {
      console.log('\n✅ PDF generated successfully!');
      console.log('📥 Download URL:', result.downloadUrl);
      console.log('⏰ Expires at:', result.expiresAt);
      console.log('\nTo download the PDF, visit:', result.downloadUrl);
    } else {
      console.log('\n❌ Failed to generate PDF');
    }
  });
});

req.on('error', (error) => {
  console.error('Error:', error.message);
  console.log('\nMake sure the server is running with: npm start');
});

req.write(data);
req.end();
